loop_delay: 0.0
components:
  - name: servo_interface
    class: servo_device_interface
    startup_delay: 3
    port: /dev/cu.usbmodem14101
    baudrate: 9600
    parity: N
    stopbits: 1
    bytesize: 8
    servo_indices: [0, 5, 4, 3, 2, 1]
    servo_directions: [1, -1, 1, -1, 1, -1]
    zero_positions: [-90, -90, -90, -90, -90, -90]
  - name: imu_interface
    class: imu_device_interface
    host: ''
    port: 5555
    timeout: 0.001
    history: 1
    file_prefix: ''
    consumers:
      - kinematics_controller
  - name: kinematics_controller
    class: kinematics_controller
    max_angle_imu: 15  # degrees
    consumers:
      - servo_interface
    rod_length: 30.5  # cm
    crank_length: 3  # cm
    servo_range: [-70, 70]  # degrees
    actuators:
      - base_joint: [11.76, -5.99, 0]  # position of base joint relative to base origin
        platform_joint: [7.252531754730542, -10.061753482699977, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 1.5707963267948966  # angle between servo crank and base x-axis
      - base_joint: [11.76, 5.99, 0]  # position of base joint relative to base origin
        platform_joint: [7.2525317547305495, 10.061753482699972, 0.0]  # position of platform joint relative to platform origin
        crank_angle: -1.5707963267948966  # angle between servo crank and base x-axis
      - base_joint: [-0.6925078313312092, 13.179458748504999, 0.0]  # position of base joint relative to base origin
        platform_joint: [5.087468245269454, 11.311753482699972, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 3.665191429188092  # angle between servo crank and base x-axis
      - base_joint: [-11.067492168668787, 7.189458748505001, 0.0]  # position of base joint relative to base origin
        platform_joint: [-12.34, 1.25, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 0.5235987755982987  # angle between servo crank and base x-axis
      - base_joint: [-11.067492168668792, -7.189458748504993, 0.0]  # position of base joint relative to base origin
        platform_joint: [-12.34, -1.25, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 5.759586531581287  # angle between servo crank and base x-axis
      - base_joint: [-0.6925078313312172, -13.179458748504999, 0.0]  # position of base joint relative to base origin
        platform_joint: [5.087468245269443, -11.311753482699975, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 2.617993877991494  # angle between servo crank and base x-axis
