loop_delay: 0.01
components:
  - name: simulation_frame
    class: simulation_frame
    grid_params: {"row": 0, "column": 0}
    width: 640
    height: 800
    bbox_limits: [[-8, 8], [-8, 8], [-1, 20]]
    pad: [40, 40, 140, 140]  # top bottom left right
  - name: servo_angle_frame
    class: graph_frame
    grid_params: {"row": 0, "column": 1}
    width: 640
    height: 800
    mode: angle
    title: Servo Angle
    xlabel: Time (s)
    ylabel: Servo Angle (deg)
    keep_time: 5  # s
  - name: keyboard_interface
    class: keyboard_device_interface
    consumers:
      - kinematics_controller
    roll_rate: 20  # degrees/s
    pitch_rate: 20  # degrees/s
    yaw_rate: 0  # degrees/s
    x_rate: 2  # cm/s
    y_rate: 2  # cm/s
    z_rate: 0  # cm/s
  - name: kinematics_controller
    class: kinematics_controller
    consumers:
      - simulation_frame
      - servo_angle_frame
    rod_length: 30.5  # cm
    crank_length: 3  # cm
    servo_range: [-70, 70]  # degrees
    actuators:
      - base_joint: [11.76, -5.99, 0]  # position of base joint relative to base origin
        platform_joint: [7.252531754730542, -10.061753482699977, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 1.5707963267948966  # angle between servo crank and base x-axis
      - base_joint: [11.76, 5.99, 0]  # position of base joint relative to base origin
        platform_joint: [7.2525317547305495, 10.061753482699972, 0.0]  # position of platform joint relative to platform origin
        crank_angle: -1.5707963267948966  # angle between servo crank and base x-axis
      - base_joint: [-0.6925078313312092, 13.179458748504999, 0.0]  # position of base joint relative to base origin
        platform_joint: [5.087468245269454, 11.311753482699972, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 3.665191429188092  # angle between servo crank and base x-axis
      - base_joint: [-11.067492168668787, 7.189458748505001, 0.0]  # position of base joint relative to base origin
        platform_joint: [-12.34, 1.25, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 0.5235987755982987  # angle between servo crank and base x-axis
      - base_joint: [-11.067492168668792, -7.189458748504993, 0.0]  # position of base joint relative to base origin
        platform_joint: [-12.34, -1.25, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 5.759586531581287  # angle between servo crank and base x-axis
      - base_joint: [-0.6925078313312172, -13.179458748504999, 0.0]  # position of base joint relative to base origin
        platform_joint: [5.087468245269443, -11.311753482699975, 0.0]  # position of platform joint relative to platform origin
        crank_angle: 2.617993877991494  # angle between servo crank and base x-axis
